<?php
// ============================================================
// report.php — Diagnosis Report page.
// Displays structured observation results generated by the
// YOLOv8 Image Recognition Module.
// ============================================================
session_start();

if (!isset($_SESSION['farmer'])) {
    header('Location: index.php');
    exit;
}
if (!isset($_SESSION['diagnosis'])) {
    header('Location: diagnose.php');
    exit;
}

$d = $_SESSION['diagnosis'];
$modelVersion = $d['model_version'] ?? 'yolo-agri-v1';
$detectionCount = isset($d['detections']) ? count($d['detections']) : 0;
$affectedArea = isset($d['affected_area_percentage']) ? (float)$d['affected_area_percentage'] : null;
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>CropGuard — Diagnosis Report</title>
<link rel="stylesheet" href="css/style.css">
<style>
.vision-badge {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  background: #e8f5e9;
  color: #2e7d32;
  font-size: 11px;
  font-weight: 700;
  padding: 4px 10px;
  border-radius: 12px;
  margin-bottom: 12px;
  letter-spacing: 0.5px;
  border: 1px solid #c8e6c9;
}
.quality-note {
  background: #f1f8e9;
  border-left: 3px solid #66bb6a;
  padding: 8px 12px;
  border-radius: 4px;
  font-size: 12px;
  color: #33691e;
  margin: 12px 0;
}
</style>
</head>
<body>

<div class="phone">
  <div class="status-bar">
    <span>9:41</span>
    <span class="icons">📶 📡 🔋</span>
  </div>

  <div class="screen">
    <div class="back-row">
      <a href="diagnose.php" class="back-circle">←</a>
      <h2>Diagnosis Report</h2>
    </div>

    <img class="report-photo" src="<?php echo htmlspecialchars($d['image_path']); ?>" alt="Uploaded leaf photo">

    <div style="display: flex; justify-content: space-between; align-items: center; margin-top: 4px;">
      <span class="severity-pill"><?php echo htmlspecialchars(strtoupper($d['severity'])); ?> SEVERITY</span>
      <span class="vision-badge">⚡ <?php echo htmlspecialchars(strtoupper($modelVersion)); ?></span>
    </div>

    <div class="disease-label">DETECTED DIAGNOSIS</div>
    <div class="disease-name"><?php echo htmlspecialchars($d['disease']); ?></div>

    <div class="meta-row"><span class="k">Target Crop: </span><span class="v"><?php echo htmlspecialchars($d['crop']); ?></span></div>
    <div class="meta-row"><span class="k">Confidence Level: </span><span class="v"><?php echo htmlspecialchars($d['confidence']); ?>% Accuracy</span></div>
    <?php if ($affectedArea !== null && $affectedArea > 0): ?>
      <div class="meta-row"><span class="k">Affected Canopy Area: </span><span class="v"><?php echo htmlspecialchars($affectedArea); ?>%</span></div>
    <?php endif; ?>
    <?php if ($detectionCount > 0): ?>
      <div class="meta-row"><span class="k">Localized Lesions: </span><span class="v"><?php echo htmlspecialchars($detectionCount); ?> box(es) detected</span></div>
    <?php endif; ?>

    <hr class="divider">

    <div class="section-title">🛡️ Recommended Precautions & Advisory</div>

    <p class="description-text"><?php echo htmlspecialchars($d['description']); ?></p>

    <?php if (!empty($d['precautions'])): ?>
      <?php foreach ($d['precautions'] as $p): ?>
        <div class="precaution-card">
          <div class="precaution-icon"><?php echo htmlspecialchars($p['icon'] ?? '🌱'); ?></div>
          <div>
            <h4><?php echo htmlspecialchars($p['title']); ?></h4>
            <p><?php echo htmlspecialchars($p['text']); ?></p>
          </div>
        </div>
      <?php endforeach; ?>
    <?php endif; ?>

    <a href="diagnose.php" class="btn btn-primary">📷 Diagnose Another Crop</a>
  </div>

  <div class="home-indicator"></div>
</div>

</body>
</html>
